### ISSUE TITLE
User story: manual implementation of semi-sealed trait

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-linting/design#20]
### Lint explanation

Some advanced unsafe traits (e.g. [`Bundle`]) are so tricky to implement correctly and the consequences so dire that they should never be manually implemented externally.

However, we need to allow users to use the foolproof derive macro, and so cannot seal the trait.

**Comment by xFrednet** [comment]
Thank you for this and the other user stories!

For reference, this is the documentation for `Bundle`: https://docs.rs/bevy/0.7.0/bevy/ecs/bundle/trait.Bundle.html (AFAIK).

Just to be certain, that I understand this lint correctly. This should check every `impl` item, if it implements the `Bundle` trait for something. Impls should only be allowed if they comes from bevy's derive macro, but not from any other source. Correct?

**Comment by alice-i-cecile** [comment]
That's exactly correct. Manual trait implementations within `bevy_ecs` should be allowed, but it's fine if that requires and allow for the handle of special cases.

**Comment by jhpratt** [comment]
I think this is largely the same as #17.

**Comment by alice-i-cecile** [comment]
Agreed. Closing in favor of #17 to keep the stories collected.
