### ISSUE TITLE
Lint `missing_safety_comment`

### ISSUE THREAD

**Issue by Veetaha** [rust-linting/design#41]
### Lint explanation

Enforce the usage of `// SAFETY:` explanatory comments on top of unsafe blocks and `# Safety` on top of unsafe functions. It is conventional to write the documentation about why the given unsafe block is safe describing how it handles the various dynamic unsafe invariants of the unsafe functions it invokes. It is also conventional to have a `# Safety` section in the docs of the unsafe function to explain why the function is unsafe and what invariants must hold for it to not invoke UB.

#### Bad

``` rust
let raw = b"foo".to_vec();
unsafe {
    let c_string = CString::from_vec_unchecked(raw);
}
```

#### Good

```rust
let raw = b"foo".to_vec();

// SAFETY: it's safe to do this, because we know the vector here doesn't contain any internal '\0' symbols
unsafe {
    let c_string = CString::from_vec_unchecked(raw);
}
```

**Comment by xFrednet** [comment]
Thank you for the issue!

Is there a reason why you don't want to use the [`clippy::undocumented_unsafe_blocks`](https://rust-lang.github.io/rust-clippy/master/index.html#/undocumented_unsafe_blocks) Clippy lint for these?

**Comment by Veetaha** [comment]
Ah, right, I didn't find that lint in clippy. I've been having the idea for this lint written down before clippy even implemented it, should've checked if they implemented it already today. I'm closing this, thanks
